config/routes.rb
Status::Application.routes.draw do
  resources :launch_statuses

  resources :features

  devise_for :users

  root :to => 'foyer#index'

  match "admin/" => "admin#index"

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  # attr_accessible :user_attributes

  belongs_to :user
  belongs_to :launch_status


  attr_accessible :about, :ended, :progress, :started, :status, :title, :user, :id, :user_id, :launch_status, :launch_status_id

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :launch_status

end

app/models/feature_launch.rb
class FeatureLaunch < ActiveRecord::Base
  belongs_to :feature
  belongs_to :launch_status
end

app/models/launch_status.rb
class LaunchStatus < ActiveRecord::Base
  has_many :features

  attr_accessible :description, :name, :id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :features
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index


    render "index"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_filter :authenticate_user!
  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new
    @user = User.all
    # @feature.user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, :notice => 'Feature was successfully created.' }
        format.json { render :json => @feature, :status => :created, :location => @feature }


      else
        format.html { render :action => "new" }
        format.json { render :json => @feature.errors, :status => :unprocessable_entity }
      end
    end
    puts @feature
    # @launch_status = @feature.launch_status.save(params[:launch_status_id])
    # @launch_status.save

  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, :notice => 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/foyer_controller.rb
class FoyerController < ApplicationController


  def index

    @features = Feature.all

    @body_id = "home"

    render "home"
  end
end

app/controllers/launch_statuses_controller.rb
class LaunchStatusesController < ApplicationController
  # GET /launch_statuses
  # GET /launch_statuses.json
  def index
    @launch_statuses = LaunchStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @launch_statuses }
    end
  end

  # GET /launch_statuses/1
  # GET /launch_statuses/1.json
  def show
    @launch_status = LaunchStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @launch_status }
    end
  end

  # GET /launch_statuses/new
  # GET /launch_statuses/new.json
  def new
    @launch_status = LaunchStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @launch_status }
    end
  end

  # GET /launch_statuses/1/edit
  def edit
    @launch_status = LaunchStatus.find(params[:id])
  end

  # POST /launch_statuses
  # POST /launch_statuses.json
  def create
    @launch_status = LaunchStatus.new(params[:launch_status])

    respond_to do |format|
      if @launch_status.save
        format.html { redirect_to @launch_status, :notice => 'Launch status was successfully created.' }
        format.json { render :json => @launch_status, :status => :created, :location => @launch_status }
      else
        format.html { render :action => "new" }
        format.json { render :json => @launch_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /launch_statuses/1
  # PUT /launch_statuses/1.json
  def update
    @launch_status = LaunchStatus.find(params[:id])

    respond_to do |format|
      if @launch_status.update_attributes(params[:launch_status])
        format.html { redirect_to @launch_status, :notice => 'Launch status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @launch_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /launch_statuses/1
  # DELETE /launch_statuses/1.json
  def destroy
    @launch_status = LaunchStatus.find(params[:id])
    @launch_status.destroy

    respond_to do |format|
      format.html { redirect_to launch_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/launch_statuses_helper.rb
module LaunchStatusesHelper
end

app/views/admin/index.html.erb
<%= link_to "features", "features" %>
<%= link_to "statuses", "launch_statuses" %>

app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :started %><br />
    <%= f.datetime_select :started %>
  </div>
  <div class="field">
    <%= f.label :ended %><br />
    <%= f.datetime_select :ended %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :launch_status %><br />
    <%= f.collection_select(:launch_status_id, LaunchStatus.all, :id, :name, {:prompt => true} ) %>
  </div>
  <div class="field">
    <%= f.label :progress %><br />
    <%= f.text_field :progress %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select(:user_id, User.all, :id, :email, {:prompt => true} ) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h1>Listing features</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Started</th>
    <th>Ended</th>
    <th>About</th>
    <th>Status</th>
    <th>Progress</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @features.each do |feature| %>
  <tr>
    <td><%= feature.title %></td>
    <td><%= feature.started %></td>
    <td><%= feature.ended %></td>
    <td><%= feature.about %></td>
    <td><%= feature.status %></td>
    <td><%= feature.progress %></td>
    <td><%= feature.user.email if feature.user %></td>
    <td><%= link_to 'Show', feature %></td>
    <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
    <td><%= link_to 'Destroy', feature, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @feature.title %>
</p>

<p>
  <b>Started:</b>
  <%= @feature.started %>
</p>

<p>
  <b>Ended:</b>
  <%= @feature.ended %>
</p>

<p>
  <b>About:</b>
  <%= @feature.about %>
</p>

<p>
  <b>Status:</b>
  <%= @feature.launch_status.name %>
</p>

<p>
  <b>Progress:</b>
  <%= @feature.progress %>
</p>

<p>
  <b>User:</b>
  <%= @feature.user.email %>
</p>


<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/foyer/home.html.erb
<style type="text/css" media="screen">



</style>

<div class="container">
  <div class="header-container">
    <h1>LaunchList</h1>
  </div>

  <div class="project-list">
    <div class="legend">
      <span class="title">Project</span>
      <span class="target">Version</span>
      <span class="status">Status</span>
    </div>

    <ul class="projects">
      <% if !@features.blank? %>
        <% for i in @features %>
             <li class="project tt">
               <h2>
                <span class="title">
                  <span class="strikethrough"></span>
                  <strong><%= i.title %></strong>
                </span>
               <span class="target">
                <span class="strikethrough"></span>
                <strong><%= i.progress %></strong>
               </span>
               <span class="status blue glow">
                <span class="strikethrough"></span>

                <strong><%= i.launch_status.name %></strong>
               </span>
             </h2>
             <p class="info title"><span class="label"><b>Info: </b></span><%= raw i.about %></p>
             <p class="crew">
              <span class="label"><b>Crew: </b></span>
               <span class="person"><%= i.user.email if i.user %></span>
             </p>
             <p class="eta"><span class="label"><b>Status:</b></span> Released on October 3rd, 2012.
              <!-- <a href="http://support.culturedcode.com/customer/portal/articles/174828" style="font-size: smaller; color: #999999; hover: none">Release Notes</a></p> -->
           </li>
        <% end %>
      <% else %>
    <% end %>
  </div>

</div>

app/views/launch_statuses/_form.html.erb
<%= form_for(@launch_status) do |f| %>
  <% if @launch_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@launch_status.errors.count, "error") %> prohibited this launch_status from being saved:</h2>

      <ul>
      <% @launch_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/launch_statuses/edit.html.erb
<h1>Editing launch_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @launch_status %> |
<%= link_to 'Back', launch_statuses_path %>

app/views/launch_statuses/index.html.erb
<h1>Listing launch_statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @launch_statuses.each do |launch_status| %>
  <tr>
    <td><%= launch_status.name %></td>
    <td><%= launch_status.description %></td>
    <td><%= link_to 'Show', launch_status %></td>
    <td><%= link_to 'Edit', edit_launch_status_path(launch_status) %></td>
    <td><%= link_to 'Destroy', launch_status, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Launch status', new_launch_status_path %>

app/views/launch_statuses/new.html.erb
<h1>New launch_status</h1>

<%= render 'form' %>

<%= link_to 'Back', launch_statuses_path %>

app/views/launch_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @launch_status.name %>
</p>

<p>
  <b>Description:</b>
  <%= @launch_status.description %>
</p>


<%= link_to 'Edit', edit_launch_status_path(@launch_status) %> |
<%= link_to 'Back', launch_statuses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Status</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>